const translations = {
  ko: {
    "nav.about": "소개",
    "nav.programs": "프로그램",
    "nav.results": "취업성과",
    "nav.path": "성장경로",
    "nav.media": "미디어",
    "nav.apply": "지원하기",
    "hero.badge": "실리콘밸리식 프로젝트와 멘토 시스템",
    "hero.title": "개발자로 성장하는 과정을 함께 경험하는 Techeer",
    "hero.copy": "테커는 SW 부트캠프를 시작으로 팀 프로젝트, 코딩테스트, 이력서, 인터뷰, 실리콘밸리 경험까지 연결하는 개발자 성장 그룹입니다.",
    "hero.cta": "지원 정보 보기",
    "hero.secondary": "프로그램 보기",
    "stats.students": "부트캠프 수료생",
    "stats.companies": "취업 기업",
    "stats.cohorts": "부트캠프 운영",
    "stats.schools": "참여 대학",
    "home.about.title": "테커는 학교 밖에서 만드는 진짜 개발자 팀입니다",
    "home.about.copy": "혼자 강의만 듣는 부트캠프가 아니라, 동료와 매일 만들고 현직 멘토에게 피드백 받으며 포트폴리오를 완성합니다.",
    "home.programs.title": "첫 부트캠프부터 취업 이후 성장까지",
    "home.results.title": "수료생들은 국내외 테크 기업에서 일하고 있습니다",
    "home.path.title": "5주 몰입 이후에도 성장 루프가 이어집니다",
    "home.media.title": "현장의 에너지와 프로젝트를 계속 공유합니다",
    "cta.title": "다음 기수에서 같이 성장할 준비가 됐다면",
    "cta.copy": "개발 경험보다 중요한 것은 끝까지 만들고 배우려는 태도입니다.",
    "cta.button": "지원하기",
    "about.title": "소개",
    "about.copy": "테커는 실리콘밸리에서 직접 운영하는 프로젝트 중심 코딩스쿨입니다. 한국 청년들이 실무형 개발자로 성장할 수 있도록 부트캠프, 멘토링, 프로젝트, 커리어 준비를 연결합니다.",
    "programs.title": "프로그램",
    "programs.copy": "5주 집중 온라인 부트캠프를 중심으로 팀 프로젝트, 해커톤, 이력서와 인터뷰 클리닉, 실리콘밸리 한 달 살기, 기술 세션을 운영합니다.",
    "results.title": "취업성과",
    "results.copy": "테커 수료생들은 Tesla, Amazon AWS, 네이버, 카카오, 토스, 삼성전자, 우아한형제들, 당근마켓 등 다양한 기업에서 커리어를 시작했습니다.",
    "path.title": "성장경로",
    "path.copy": "테커는 단기 교육에서 끝나지 않습니다. 부트캠프 이후 고성과자는 테커 그룹에 합류해 프로젝트와 멘토 역할을 경험하며 경력 있는 신입으로 성장합니다.",
    "media.title": "미디어",
    "media.copy": "부트캠프 결과 발표, 테커 파티, 해커톤, 실리콘밸리 활동 등 테커의 현장을 모았습니다.",
    "apply.title": "지원하기",
    "apply.copy": "다음 SW 부트캠프와 테커 활동에 관심 있다면 이메일 또는 공식 채널로 문의해주세요.",
    "footer.copy": "Technology + Career. 실리콘밸리에서 시작하는 개발자의 성장 여정."
  },
  en: {
    "nav.about": "About",
    "nav.programs": "Programs",
    "nav.results": "Outcomes",
    "nav.path": "Growth Path",
    "nav.media": "Media",
    "nav.apply": "Apply",
    "hero.badge": "Silicon Valley style projects and mentoring",
    "hero.title": "Techeer helps young developers grow through real teams",
    "hero.copy": "Techeer is a developer growth group that connects SW bootcamps, team projects, coding tests, resumes, interviews, and Silicon Valley experiences.",
    "hero.cta": "See application info",
    "hero.secondary": "Explore programs",
    "stats.students": "Bootcamp graduates",
    "stats.companies": "Hiring companies",
    "stats.cohorts": "Bootcamp cohorts",
    "stats.schools": "Partner schools",
    "home.about.title": "A real developer team beyond school",
    "home.about.copy": "Students build daily with peers, receive feedback from working mentors, and turn projects into job-ready portfolios.",
    "home.programs.title": "From the first bootcamp to long-term career growth",
    "home.results.title": "Graduates now work across Korean and global tech companies",
    "home.path.title": "Growth continues after the 5-week sprint",
    "home.media.title": "Follow the energy of projects, events, and demos",
    "cta.title": "Ready to grow with the next cohort?",
    "cta.copy": "Prior experience matters less than the attitude to keep building and learning.",
    "cta.button": "Apply",
    "about.title": "About",
    "about.copy": "Techeer is a project-driven coding school operated from Silicon Valley. It connects bootcamps, mentoring, projects, and career preparation for young Korean developers.",
    "programs.title": "Programs",
    "programs.copy": "Programs include a 5-week online bootcamp, team projects, hackathons, resume and interview clinics, Silicon Valley immersion, and technical sessions.",
    "results.title": "Outcomes",
    "results.copy": "Techeer graduates have started careers at Tesla, Amazon AWS, Naver, Kakao, Toss, Samsung, Woowa Brothers, Karrot, and more.",
    "path.title": "Growth Path",
    "path.copy": "Techeer is not a one-time class. High performers join the Techeer group, build portfolio projects, mentor others, and become job-ready developers.",
    "media.title": "Media",
    "media.copy": "Explore bootcamp demos, Techeer parties, hackathons, and Silicon Valley moments.",
    "apply.title": "Apply",
    "apply.copy": "Contact us by email or official channels if you are interested in the next SW bootcamp or Techeer activities.",
    "footer.copy": "Technology + Career. A developer growth journey from Silicon Valley."
  }
};

const textTranslations = {
  "소개 | Techeer": "About | Techeer",
  "지원하기 | Techeer": "Apply | Techeer",
  "Techeer | 실리콘밸리 성장 코딩스쿨": "Techeer | Silicon Valley Growth Coding School",
  "미디어 | Techeer": "Media | Techeer",
  "성장경로 | Techeer": "Growth Path | Techeer",
  "프로그램 | Techeer": "Programs | Techeer",
  "취업성과 | Techeer": "Outcomes | Techeer",
  "프로그램은 매년 6월 말과 12월 말에 시작합니다.": "Programs start every year in late June and late December.",
  "운영 방식": "Format",
  "5주 집중 과정 + 커뮤니티 트랙": "5-week sprint + community track",
  "시작 시기": "Start Windows",
  "매년 6월 말과 12월 말": "Late June and late December every year",
  "집중 영역": "Focus",
  "프로젝트, 코드 리뷰, 커리어 준비": "Project, code review, career prep",
  "결과물": "Outcome",
  "포트폴리오용 팀 프로젝트": "Portfolio-ready team project",
  "수료생": "Graduates",
  "부트캠프 수료생 1,000명+": "1,000+ bootcamp alumni",
  "입사 기업 200곳+": "200+ hiring companies",
  "참여 대학 34개": "34 participating universities",
  "프로그램 보기": "View Programs",
  "지원 문의": "Application Inquiry",
  "함께 경험하고 성장하는 개발자 그룹": "A developer group that learns and grows together",
  "프로젝트, 멘토링, 발표 중심 성장": "Growth through projects, mentoring, and demos",
  "부트캠프 이후에도 이어지는 네트워크": "A network that continues after bootcamp",
  "혼자 공부하는 시간을 팀으로 일하는 경험으로 바꿉니다": "Turn solo study into real team-based development experience",
  "테커는 지식 전달보다 경험 설계에 집중합니다. 팀으로 만들고, 발표하고, 피드백 받고, 다시 개선하는 루프가 핵심입니다.": "Techeer focuses less on delivering lectures and more on designing experience. The core loop is building as a team, presenting, receiving feedback, and improving again.",
  "실리콘밸리 운영 방식": "Silicon Valley operating model",
  "기회는 열고 성과는 명확하게 보상하는 시스템으로 자발적 성장을 만듭니다.": "We create voluntary growth through open opportunity and clear performance-based recognition.",
  "멘토 중심 피드백": "Mentor-led feedback",
  "현직 개발자와 선배 멘토가 프로젝트, 커리어, 학습 방향을 함께 점검합니다.": "Working engineers and senior mentors review projects, career direction, and learning plans together.",
  "커뮤니티 기반 성장": "Community-based growth",
  "부트캠프 이후에도 프로젝트, 스터디, 기술 세션을 통해 성장 루프를 이어갑니다.": "After bootcamp, members continue growing through projects, study groups, and technical sessions.",
  "테커가 보는 좋은 개발자의 기준": "What Techeer looks for in a strong developer",
  "맡은 기능을 끝까지 설명하고 개선합니다.": "Own features end to end, explain decisions, and keep improving.",
  "코드와 의사결정을 팀원에게 투명하게 공유합니다.": "Share code and technical decisions transparently with the team.",
  "작게 만들고 빠르게 검증하며 다음 버전으로 나아갑니다.": "Build small, validate quickly, and move to the next version.",
  "배우려는 태도와 책임감으로 피드백을 빠르게 반영합니다.": "Bring a learning mindset and accountability, and apply feedback quickly.",
  "Technology + Career. 실리콘밸리에서 시작하는 개발자의 성장 여정.": "Technology + Career. A developer growth journey starting from Silicon Valley.",
  "이메일 문의": "Email Inquiry",
  "개발자로 성장하고 싶은 대학생/청년": "Students and young adults who want to become developers",
  "5주 프로젝트 몰입과 팀 협업": "5 weeks of project focus and team collaboration",
  "공식 채널에서 모집 일정 안내": "Recruiting schedules are announced through official channels",
  "모집 상태": "Application Status",
  "현재 진행 중인 프로그램 신청은 없습니다.": "There are no program applications open right now.",
  "2026년 6월에 시작하는 프로그램은 5월 말부터 신청을 접수합니다.": "Applications for the program starting in June 2026 will open in late May.",
  "다음 부트캠프 모집 일정은 공식 채널을 통해 공지합니다. 관심이 있다면 이메일로 이름, 학교/소속, 관심 분야를 남겨주세요.": "The next bootcamp schedule will be announced through official channels. If interested, email us your name, school or affiliation, and area of interest.",
  "지원 전 확인하면 좋은 것": "What to check before applying",
  "5주 동안 프로젝트에 몰입할 시간": "Time to focus on the project for 5 weeks",
  "팀원과 매일 소통하고 피드백을 받는 태도": "A willingness to communicate daily and receive feedback",
  "완성도 높은 포트폴리오를 만들겠다는 목표": "A goal to build a strong portfolio",
  "취업 준비까지 이어갈 의지": "Commitment to continue through career preparation",
  "1. 문의": "1. Inquiry",
  "이메일 또는 공식 SNS로 관심 기수와 현재 상황을 알려주세요.": "Contact us by email or official social channels with your target cohort and current situation.",
  "2. 모집 안내 확인": "2. Check Recruiting Details",
  "모집 시기, 참가 조건, 운영 방식을 확인한 뒤 지원을 준비합니다.": "Review the schedule, eligibility, and operating model before applying.",
  "3. 프로젝트 몰입": "3. Project Immersion",
  "합류 후에는 팀과 함께 매주 결과물을 만들고 발표합니다.": "After joining, you build and present weekly outcomes with your team.",
  "실리콘밸리식 프로젝트와 멘토 시스템": "Silicon Valley-style projects and mentoring",
  "개발자로 성장하는 과정을 함께 경험하는 Techeer": "Techeer helps you experience the full journey of becoming a developer",
  "테커는 SW 부트캠프를 시작으로 팀 프로젝트, 코딩테스트, 이력서, 인터뷰, 실리콘밸리 경험까지 연결하는 개발자 성장 그룹입니다.": "Techeer is a developer growth group connecting SW bootcamps, team projects, coding tests, resumes, interviews, and Silicon Valley experiences.",
  "지원 정보 보기": "View Application Info",
  "부트캠프 수료생": "Bootcamp Graduates",
  "취업 기업": "Hiring Companies",
  "11기": "11 cohorts",
  "부트캠프 운영": "Bootcamp Cohorts",
  "34개": "34 schools",
  "참여 대학": "Participating Universities",
  "테커는 학교 밖에서 만드는 진짜 개발자 팀입니다": "Techeer is a real developer team built beyond school",
  "혼자 강의만 듣는 부트캠프가 아니라, 동료와 매일 만들고 현직 멘토에게 피드백 받으며 포트폴리오를 완성합니다.": "Instead of watching lectures alone, you build daily with peers, receive feedback from working mentors, and complete your portfolio.",
  "5주 동안 실제 서비스처럼 기획, 개발, 배포, 발표까지 경험합니다.": "For 5 weeks, you experience planning, development, deployment, and presentation like a real service team.",
  "실리콘밸리와 국내 현직 개발자 피드백으로 학습 방향을 빠르게 잡습니다.": "Feedback from Silicon Valley and Korean working engineers helps you set the right learning direction quickly.",
  "코딩테스트, 이력서, 인터뷰까지 취업에 필요한 마지막 단계를 함께 준비합니다.": "We prepare the final career steps together, including coding tests, resumes, and interviews.",
  "테커의 성장은 한눈에 보이는 구조로 움직입니다": "Techeer's growth system is easy to scan at a glance",
  "지원자는 5주 부트캠프에서 팀 프로젝트를 완성하고, 커리어 준비와 커뮤니티 활동으로 다음 단계의 개발자 역량을 증명합니다.": "Participants complete a team project in the 5-week bootcamp, then prove the next level of developer capability through career preparation and community activity.",
  "5주 몰입": "5-week focus",
  "팀 빌드와 배포": "Team build and deployment",
  "이력서와 인터뷰": "Resume and interview",
  "멘토 성장": "Mentor growth",
  "단계": "Stage",
  "핵심 활동": "Core Activity",
  "보이는 결과": "Visible Outcome",
  "개발 기본기, Git 협업, 주차별 미션": "Development fundamentals, Git collaboration, weekly missions",
  "5주 동안 작동하는 서비스 데모": "Working service demo after 5 weeks",
  "프론트엔드, 백엔드, 인프라 역할 분담": "Frontend, backend, and infrastructure role split",
  "포트폴리오에 담을 팀 프로젝트": "Team project for a portfolio",
  "코딩테스트, 이력서, 기술 면접 준비": "Coding tests, resume, and technical interview prep",
  "채용 담당자에게 설명 가능한 경험": "Experience that can be explained to hiring teams",
  "첫 부트캠프부터 취업 이후 성장까지": "From your first bootcamp to growth after employment",
  "매년 2회 열리는 5주 집중 온라인 부트캠프.": "A 5-week intensive online bootcamp held twice a year.",
  "프론트엔드, 백엔드, 인프라 역할을 나누어 완성도 높은 프로젝트를 만듭니다.": "Teams divide frontend, backend, and infrastructure roles to build polished projects.",
  "실리콘밸리 한 달 살기와 글로벌 네트워킹으로 시야를 넓힙니다.": "Silicon Valley immersion and global networking expand your career perspective.",
  "수료생들은 국내외 테크 기업에서 일하고 있습니다": "Graduates work at tech companies in Korea and abroad",
  "네이버": "Naver",
  "카카오": "Kakao",
  "토스": "Toss",
  "삼성전자": "Samsung Electronics",
  "우아한형제들": "Woowa Brothers",
  "당근마켓": "Karrot",
  "크래프톤": "Krafton",
  "현대자동차": "Hyundai Motor",
  "현장의 에너지와 프로젝트를 계속 공유합니다": "We keep sharing the energy of projects and events",
  "부트캠프 발표회, 해커톤, 테커 파티, 기술 블로그를 통해 함께 성장하는 장면을 기록합니다.": "We document growth through bootcamp demos, hackathons, Techeer parties, and technical blogs.",
  "다음 기수에서 같이 성장할 준비가 됐다면": "If you are ready to grow with the next cohort",
  "개발 경험보다 중요한 것은 끝까지 만들고 배우려는 태도입니다.": "More important than prior experience is the attitude to keep building and learning.",
  "현장 보기": "View Stories",
  "부트캠프 우수팀 발표": "Bootcamp top team demos",
  "해커톤과 테커 파티": "Hackathons and Techeer parties",
  "기술 블로그와 프로젝트 기록": "Tech blogs and project archives",
  "프로젝트가 완성되는 장면들": "Scenes where projects come together",
  "결과 발표, 이벤트, 네트워킹 현장을 통해 테커 커뮤니티의 분위기와 실행력을 확인할 수 있습니다.": "Through demos, events, and networking scenes, you can see the energy and execution of the Techeer community.",
  "외부 미디어가 본 Techeer": "Techeer in external media",
  "테커의 시작점, 운영 철학, 그리고 학생들이 개발자로 성장하는 방식이 외부 미디어에 소개되었습니다.": "External media has covered Techeer's origin, operating philosophy, and how students grow into developers.",
  "포춘코리아 VISION REPORT": "Fortune Korea Vision Report",
  "자발성을 설계하는 엔지니어": "An engineer who designs self-driven growth",
  "포춘코리아는 박상현 대표가 실리콘밸리에서 경험한 성장 방식과 성과 기반 보상 구조를 한국 청년 교육에 적용한 배경을 소개했습니다.": "Fortune Korea covered how founder Sanghyun Park applied Silicon Valley growth practices and performance-based reward structures to education for young Koreans.",
  "지방대에서 실리콘밸리까지 이어진 커리어 경험": "A career journey from a regional university to Silicon Valley",
  "기회는 공평하게, 보상은 성과에 따라 차등 지급하는 운영 철학": "An operating philosophy of equal opportunity and performance-based rewards",
  "프로젝트와 멘토링을 통해 전문 개발자로 성장하는 커뮤니티 구조": "A community structure where projects and mentoring help members become professional developers",
  "테커가 주목받는 이유": "Why Techeer is drawing attention",
  "테커는 단기 강의형 교육이 아니라, 학생이 스스로 프로젝트를 완성하고 동료와 멘토의 피드백 속에서 성장하도록 설계된 시스템이라는 점에서 소개되었습니다.": "Techeer was introduced as a system designed for students to complete projects and grow through peer and mentor feedback, not as a short lecture-based course.",
  "영상으로 보는 Techeer": "Techeer in videos",
  "테커 소개 영상과 부트캠프 우수팀 발표 영상을 통해 실제 프로그램의 분위기와 결과물을 확인할 수 있습니다.": "Intro videos and bootcamp demo videos show the actual program atmosphere and outcomes.",
  "머니투데이 티타임즈": "MoneyToday TTimes",
  "\"여러분은 생각도 못할 대학 출신입니다\"": "\"I graduated from a university you would never expect\"",
  "SKY 출신이 아니어도 전문성 있는 SW 엔지니어로 성장하는 방법을 소개한 영상입니다.": "A video about how to grow into a professional software engineer even without a SKY university background.",
  "티타임즈": "TTimes",
  "테커 소개 영상": "Techeer introduction video",
  "테커가 왜 만들어졌고 어떤 방식으로 학생들의 성장을 돕는지 확인할 수 있습니다.": "See why Techeer was created and how it helps students grow.",
  "11기 최우수팀 발표": "Cohort 11 best team demo",
  "부트캠프 참가팀이 프로젝트 결과물을 발표하는 데모 영상입니다.": "A demo video where bootcamp teams present their project outcomes.",
  "우수팀 발표 영상과 프로젝트 결과를 통해 테커의 프로젝트 수준을 확인할 수 있습니다.": "Top team demos and project outcomes show the quality of Techeer projects.",
  "매년 업계 전문가, 멘토, 멤버가 모여 성장을 공유합니다.": "Every year, industry experts, mentors, and members gather to share growth.",
  "테커 멤버들이 개발 경험과 기술 학습을 글로 남깁니다.": "Techeer members write about development experience and technical learning.",
  "테커 단계별 코딩 교육 모델": "Techeer's step-by-step coding education model",
  "테커는 5주 부트캠프에서 끝나는 교육이 아니라, 프로젝트 수행, 커리어 준비, 멘토 성장까지 이어지는 단계형 개발자 성장 모델입니다.": "Techeer is not a program that ends after a 5-week bootcamp. It is a staged developer growth model that continues through projects, career preparation, and mentor growth.",
  "프로그램 확인": "Check Programs",
  "5주 집중 부트캠프": "5-week intensive bootcamp",
  "팀 프로젝트와 포트폴리오": "Team projects and portfolio",
  "취업 이후 멘토 성장": "Mentor growth after employment",
  "단계별 목표가 명확해야 성장이 보입니다": "Clear goals at each stage make growth visible",
  "각 단계는 참가자가 무엇을 배우는지, 어떤 결과물을 만들어야 하는지, 다음 단계로 이동하기 위해 무엇을 증명해야 하는지 기준을 둡니다. 그래서 테커의 성장경로는 단순 수료 과정이 아니라 개발자로 일할 준비를 만드는 모델입니다.": "Each stage defines what participants learn, what they produce, and what they must prove to move forward. That makes Techeer's growth path a model for becoming job-ready, not just a completion track.",
  "입문 진단과 몰입 준비": "Entry diagnosis and immersion preparation",
  "개발 경험과 관계없이 현재 수준을 확인하고, 5주 동안 몰입할 학습 루틴과 협업 태도를 정렬합니다.": "Regardless of prior experience, participants identify their current level and align learning routines and collaboration habits for 5 weeks of focus.",
  "목표": "Goal",
  "기초 역량과 성장 의지 확인": "Confirm basic ability and growth mindset",
  "산출물": "Output",
  "학습 계획, 관심 직무, 팀 협업 준비": "Learning plan, target role, team collaboration readiness",
  "5주 SW 부트캠프": "5-week SW bootcamp",
  "온라인 집중 과정에서 개발 기본기, Git 협업, API 연동, 배포 흐름을 프로젝트 중심으로 익힙니다.": "In the intensive online program, participants learn development fundamentals, Git collaboration, API integration, and deployment through projects.",
  "개발자로 일하는 기본 루프 습득": "Learn the core loop of working as a developer",
  "주차별 과제, 팀 프로젝트 데모": "Weekly assignments and team project demos",
  "테커 그룹 프로젝트": "Techeer group projects",
  "고성과자는 테커 그룹에 합류해 실제 서비스 수준의 프로젝트를 수행하고 포트폴리오를 고도화합니다.": "High performers join the Techeer group, build service-level projects, and strengthen their portfolios.",
  "실전형 프로젝트 경험 축적": "Build practical project experience",
  "배포 서비스, GitHub 기록, 발표 자료": "Deployed service, GitHub history, presentation materials",
  "커리어 완성 과정": "Career completion track",
  "코딩테스트, 이력서, 기술 면접을 준비하며 프로젝트 경험을 채용 담당자가 이해할 수 있는 언어로 정리합니다.": "Participants prepare for coding tests, resumes, and technical interviews while translating project experience into hiring language.",
  "지원 가능한 개발자 프로필 완성": "Complete an application-ready developer profile",
  "이력서, 포트폴리오, 면접 답변 구조": "Resume, portfolio, and interview answer structure",
  "실리콘밸리 경험과 네트워킹": "Silicon Valley experience and networking",
  "현지 기업 탐방, 엔지니어 네트워킹, 글로벌 개발 문화 경험을 통해 커리어 시야를 넓힙니다.": "Company visits, engineer networking, and global development culture broaden career perspective.",
  "글로벌 기준과 커리어 관점 확장": "Expand global standards and career perspective",
  "네트워크, 회고, 장기 성장 계획": "Network, reflection, and long-term growth plan",
  "멘토 성장과 리더십": "Mentor growth and leadership",
  "취업 이후에는 후배를 돕는 멘토, 시니어 멘토, 디렉터 역할로 성장하며 커뮤니티에 기여합니다.": "After employment, members contribute to the community as mentors, senior mentors, and directors.",
  "개발자 이후의 리더십 성장": "Leadership growth after becoming a developer",
  "멘토링, 기술 세션, 운영 기여": "Mentoring, technical sessions, and operational contribution",
  "부트캠프에서 전문 개발자까지": "From bootcamp to professional developer",
  "테커는 참가자가 다음 단계로 이동할 수 있도록 명확한 마일스톤을 둡니다.": "Techeer sets clear milestones so participants can move to the next stage.",
  "SW 부트캠프 참가": "Join the SW bootcamp",
  "5주 집중 온라인 부트캠프에서 개발 몰입 경험을 시작합니다.": "Start with a 5-week intensive online bootcamp.",
  "테커 그룹 합류": "Join the Techeer group",
  "고성과자는 테커 그룹 활동에 참여해 더 깊은 프로젝트와 커뮤니티를 경험합니다.": "High performers join Techeer group activities for deeper projects and community experience.",
  "팀 프로젝트 수행": "Run team projects",
  "실제 서비스 수준의 팀 프로젝트로 개발자 포트폴리오를 완성합니다.": "Complete a developer portfolio through service-level team projects.",
  "취업 준비 완성": "Complete career preparation",
  "코딩테스트, 이력서, 기술 면접을 실전 중심으로 준비합니다.": "Prepare for coding tests, resumes, and technical interviews with a practical focus.",
  "전문 개발자로 성장": "Grow into a professional developer",
  "취업 이후에도 멘토, 시니어 멘토, 디렉터로 성장하며 커뮤니티에 기여합니다.": "After employment, members continue contributing to the community as mentors, senior mentors, and directors.",
  "다음 단계로 이동하는 기준": "Criteria for moving to the next stage",
  "테커는 결과만 보지 않습니다. 문제를 정의하는 방식, 팀과 소통하는 태도, 피드백을 반영하는 속도까지 함께 봅니다.": "Techeer evaluates not only outcomes, but also problem definition, communication with the team, and the speed of applying feedback.",
  "기능 구현, 배포, 발표까지 이어지는 실제 결과물": "Real outcomes covering implementation, deployment, and presentation",
  "읽기 쉬운 코드, Git 사용, 리뷰 반영, 문제 해결 과정": "Readable code, Git usage, review reflection, and problem-solving process",
  "역할 책임, 커뮤니케이션, 일정 관리, 동료 피드백": "Role ownership, communication, schedule management, and peer feedback",
  "이력서, 포트폴리오, 인터뷰에서 경험을 설명하는 능력": "Ability to explain experience in resumes, portfolios, and interviews",
  "경력 있는 신입": "Job-ready junior developer",
  "프로젝트 경험과 커뮤니케이션 역량을 함께 갖춘 지원자로 성장합니다.": "Grow into a candidate with both project experience and communication skills.",
  "선순환 멘토링": "Mentoring flywheel",
  "먼저 성장한 멤버가 다음 기수의 멘토가 되어 커뮤니티의 기준을 높입니다.": "Members who grow first become mentors for the next cohort and raise the community standard.",
  "지속적인 자기개발": "Continuous self-development",
  "취업 이후에도 기술 세션과 네트워킹으로 학습 흐름을 유지합니다.": "Even after employment, technical sessions and networking keep the learning flow alive.",
  "모집 문의하기": "Ask About Recruiting",
  "커리큘럼 보기": "View Curriculum",
  "강의보다 중요한 것은 매주 검증되는 성장입니다": "What matters more than lectures is weekly verified growth",
  "Techeer 프로그램은 단순 수강형 과정이 아니라, 프로젝트 산출물과 피드백 루프를 중심으로 설계된 성장 시스템입니다. 참가자는 팀 단위로 문제를 정의하고, 구현하고, 발표하면서 개발자로 일하는 방식을 익힙니다.": "Techeer is not a simple lecture-based course. It is a growth system built around project outputs and feedback loops. Participants define problems, implement solutions, and present as teams.",
  "5주": "5 weeks",
  "집중 온라인 부트캠프": "Intensive online bootcamp",
  "팀 단위": "Team-based",
  "기획, 개발, 배포, 발표": "Planning, development, deployment, presentation",
  "커뮤니티 기반 학습 환경": "Community-based learning environment",
  "커리어": "Career",
  "이력서, 코딩테스트, 인터뷰": "Resume, coding tests, interviews",
  "핵심 프로그램": "Core Programs",
  "부트캠프, 프로젝트, 커리어 준비가 따로 움직이지 않도록 하나의 흐름으로 연결했습니다.": "Bootcamp, projects, and career preparation are connected as one flow.",
  "SW 부트캠프": "SW Bootcamp",
  "매년 2회 운영되는 5주 집중 온라인 과정입니다. 개발 기본기, 협업 방식, 프로젝트 실행력을 짧은 기간에 끌어올립니다.": "A 5-week intensive online program operated twice a year. It quickly raises development fundamentals, collaboration habits, and project execution ability.",
  "온라인 집중 운영": "Intensive online operation",
  "주차별 프로젝트 마일스톤": "Weekly project milestones",
  "멘토 피드백 기반 개선": "Improvement based on mentor feedback",
  "팀 프로젝트": "Team Projects",
  "프론트엔드, 백엔드, 인프라 역할을 나누어 실제 서비스에 가까운 결과물을 만듭니다.": "Teams divide frontend, backend, and infrastructure roles to build outputs close to real services.",
  "기획부터 배포까지 경험": "Experience from planning to deployment",
  "GitHub 협업과 코드 리뷰": "GitHub collaboration and code review",
  "포트폴리오 결과물 완성": "Portfolio-ready outcome",
  "해커톤": "Hackathon",
  "짧은 시간 안에 아이디어를 검증하고 구현하는 집중 개발 이벤트입니다. 문제 정의와 실행 속도를 훈련합니다.": "An intensive development event where teams validate and implement ideas quickly. It trains problem definition and execution speed.",
  "아이디어 검증": "Idea validation",
  "프로토타입 구현": "Prototype implementation",
  "데모와 발표": "Demo and presentation",
  "커리어 클리닉": "Career Clinic",
  "코딩테스트, 이력서, 기술 면접을 실전 기준으로 점검합니다. 프로젝트 경험이 채용 언어로 전달되도록 정리합니다.": "We review coding tests, resumes, and technical interviews against real hiring standards, turning project experience into hiring language.",
  "이력서 구조화": "Resume structuring",
  "기술 면접 준비": "Technical interview preparation",
  "코딩테스트 루틴": "Coding test routine",
  "실리콘밸리 한 달 살기": "One month in Silicon Valley",
  "현지 기업 탐방과 엔지니어 네트워킹을 통해 글로벌 커리어 관점과 개발 문화의 기준을 경험합니다.": "Participants experience global career perspectives and engineering culture through company visits and engineer networking.",
  "현지 네트워킹": "Local networking",
  "기업 탐방": "Company visits",
  "글로벌 커리어 관점": "Global career perspective",
  "기술 세션 & 커뮤니티": "Technical Sessions & Community",
  "현업 기술과 커리어 주제를 지속적으로 공유합니다. 부트캠프 이후에도 동료와 멘토의 학습 네트워크가 이어집니다.": "We continuously share practical technical and career topics. The learning network of peers and mentors continues after bootcamp.",
  "기술 발표": "Technical talks",
  "스터디 운영": "Study group operation",
  "선배 멘토 네트워크": "Senior mentor network",
  "실리콘밸리에서 배우고, 테커 파티에서 성장을 공유합니다": "Learn in Silicon Valley and share growth at Techeer Party",
  "테커는 부트캠프 이후에도 현지 기업 탐방, 엔지니어 네트워킹, CES·Apple·Google 등 글로벌 개발 문화 경험으로 시야를 넓힙니다. 테커 파티에서는 멘토와 멤버가 모여 프로젝트 성과와 다음 성장을 나눕니다.": "After bootcamp, Techeer expands participants' perspective through company visits, engineer networking, and global development culture experiences such as CES, Apple, and Google. At Techeer Party, mentors and members gather to share project outcomes and next growth.",
  "현지 기업 탐방과 엔지니어 네트워킹으로 글로벌 커리어 기준을 경험합니다.": "Experience global career standards through local company visits and engineer networking.",
  "성과 발표와 네트워킹을 통해 커뮤니티 안에서 다음 기회를 만듭니다.": "Create the next opportunity inside the community through outcome sharing and networking.",
  "참가자는 매주 결과물을 남깁니다": "Participants produce outcomes every week",
  "프로그램은 학습량보다 실행 밀도를 중요하게 봅니다. 매주 팀의 결과물을 만들고, 리뷰하고, 발표하면서 자신이 어디까지 성장했는지 확인합니다.": "The program values execution density more than study volume. Each week, teams build, review, and present outcomes to see how far they have grown.",
  "실제 서비스를 목표로 기능을 구현합니다.": "Build features toward a real service.",
  "멘토와 동료 피드백으로 코드와 의사결정을 개선합니다.": "Improve code and decisions through mentor and peer feedback.",
  "개발 과정을 설명하고 결과물을 설득력 있게 발표합니다.": "Explain the development process and present outcomes persuasively.",
  "다음 프로그램에 합류할 준비가 되셨나요?": "Ready to join the next program?",
  "모집 일정과 참가 조건은 공식 채널을 통해 안내합니다. 관심이 있다면 먼저 문의를 남겨주세요.": "Recruiting schedules and eligibility are announced through official channels. If interested, contact us first.",
  "Techeer 프로그램은 매년 6월 말과 12월 말에 시작합니다. 모집 일정과 참가 조건은 공식 채널을 통해 안내합니다.": "Techeer programs start every year in late June and late December. Recruiting schedules and eligibility are announced through official channels.",
  "기업 보기": "View Companies",
  "성장경로 보기": "View Growth Path",
  "운영 완료": "Completed cohorts",
  "국내외 테크 기업으로 이어지는 커리어": "Careers connected to Korean and global tech companies",
  "테커의 목표는 수료가 아니라 개발자로 일할 수 있는 실력과 포트폴리오를 완성하는 것입니다.": "Techeer's goal is not completion. It is to build the skills and portfolio needed to work as a developer.",
  "에이블리": "Ably",
  "캐치테이블": "Catch Table",
  "안랩": "AhnLab",
  "무신사": "Musinsa",
  "넥슨": "Nexon",
  "베어로보틱스": "Bear Robotics",
  "취업 회사 목록": "Hiring Company List",
  "공개 가능한 범위에서 주요 입사 기업과 관련 정보를 정리했습니다. 개인정보 보호를 위해 이름은 마스킹했습니다.": "Key hiring companies and related information are summarized within the publicly shareable scope. Names are masked for privacy.",
  "구분": "Category",
  "회사": "Company",
  "지역/분야": "Region / Field",
  "공개 사례": "Public Case",
  "비고": "Notes",
  "글로벌": "Global",
  "연세대 신**": "Yonsei Univ. Shin**",
  "글로벌 테크 기업": "Global tech company",
  "이화여대 김**": "Ewha Womans Univ. Kim**",
  "클라우드 인프라": "Cloud infrastructure",
  "사이버 보안": "Cybersecurity",
  "공개 사례 보유": "Public case available",
  "글로벌 제품 기업": "Global product company",
  "국내 빅테크": "Korean Big Tech",
  "중앙대 김**, 충남대 김**": "Chung-Ang Univ. Kim**, Chungnam National Univ. Kim**",
  "국내 대표 플랫폼": "Major Korean platform",
  "핀테크": "Fintech",
  "명지대 김**, 중앙대 곽**, 충남대 김**, 한국공학대 김**, 한국공학대 최**": "Myongji Univ. Kim**, Chung-Ang Univ. Kwak**, Chungnam National Univ. Kim**, Tech Univ. of Korea Kim**, Tech Univ. of Korea Choi**",
  "5명 입사 사례": "5 hiring cases",
  "대기업": "Enterprise",
  "국내 대기업": "Korean enterprise",
  "스타트업": "Startup",
  "인천대 김**": "Incheon National Univ. Kim**",
  "서비스 개발": "Service development",
  "충북대 신**": "Chungbuk National Univ. Shin**",
  "게임/콘텐츠": "Game / Content",
  "서강대 조**, 연세대 상**": "Sogang Univ. Cho**, Yonsei Univ. Sang**",
  "게임 테크": "Game tech",
  "모빌리티": "Mobility",
  "커머스": "Commerce",
  "플랫폼 서비스": "Platform service",
  "보안": "Security",
  "보안 기업": "Security company",
  "패션/커머스": "Fashion / Commerce",
  "커머스 플랫폼": "Commerce platform",
  "게임": "Game",
  "게임 기업": "Game company",
  "로보틱스": "Robotics",
  "로봇 서비스": "Robot service",
  "프로젝트로 증명": "Proven through projects",
  "팀 프로젝트 결과물을 기반으로 실무형 역량을 설명할 수 있게 만듭니다.": "Participants learn to explain practical capability through team project outcomes.",
  "인터뷰 언어로 정리": "Translate experience into interview language",
  "기술 선택, 장애 해결, 협업 경험을 면접에서 전달 가능한 구조로 정리합니다.": "Technical choices, troubleshooting, and collaboration experience are structured for interviews.",
  "커뮤니티 레퍼런스": "Community reference",
  "선배 멘토와 동료 네트워크를 통해 취업 준비의 기준을 계속 업데이트합니다.": "Senior mentors and peer networks keep career preparation standards up to date."
};

const reverseTextTranslations = Object.fromEntries(
  Object.entries(textTranslations).map(([ko, en]) => [en, ko])
);

const pageMeta = {
  "index.html": "home",
  "about.html": "about",
  "programs.html": "programs",
  "results.html": "results",
  "path.html": "path",
  "media.html": "media",
  "apply.html": "apply"
};

function setLanguage(lang) {
  const dict = translations[lang] || translations.ko;
  document.documentElement.lang = lang;
  localStorage.setItem("techeer-lang", lang);
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dict[key]) node.innerHTML = dict[key];
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.lang === lang);
  });
  applyVisibleTextTranslations(lang);
}

function applyVisibleTextTranslations(lang) {
  const map = lang === "en" ? textTranslations : reverseTextTranslations;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent || ["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) {
        return NodeFilter.FILTER_REJECT;
      }
      return node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
    }
  });

  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach((node) => {
    const raw = node.nodeValue;
    const key = raw.trim();
    if (!map[key]) return;
    const prefix = raw.match(/^\s*/)[0];
    const suffix = raw.match(/\s*$/)[0];
    node.nodeValue = `${prefix}${map[key]}${suffix}`;
  });
}

function currentPage() {
  const name = location.pathname.split("/").pop() || "index.html";
  return pageMeta[name] || "home";
}

document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("techeer-lang") || "ko";
  setLanguage(savedLang);

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.addEventListener("click", () => setLanguage(button.dataset.lang));
  });

  const page = currentPage();
  document.querySelectorAll(`[data-page="${page}"]`).forEach((link) => {
    link.classList.add("is-active");
  });

  const menuButton = document.querySelector("[data-menu-button]");
  const navLinks = document.querySelector("[data-nav-links]");
  if (menuButton && navLinks) {
    menuButton.addEventListener("click", () => navLinks.classList.toggle("is-open"));
  }

  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.12 });

  document.querySelectorAll("[data-animate]").forEach((node) => observer.observe(node));
});
